spring:
  application:
    name: calendarioCondiviso
  
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: "validate"

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
           enable: true

jwt:
  secret: ${JWT_SECRET}
  accessTokenExp: ${JWT_ACCESS_TOKEN_EXP}
  refreshTokenExp: ${JWT_REFRESH_TOKEN_EXP}
   
  