spring:
  application:
    name: calendarioCondiviso
  
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: "validate"

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExp: ${JWT_ACCESS_TOKEN_EXP}
    refreshTokenExp: ${JWT_ACCESS_TOKEN_EXP}
   
  